#!/bin/bash

# Script de configuración para despliegue en Render
# Variables de entorno recomendadas para MongoDB Atlas

echo "🚀 Configuración para Render - MongoDB Atlas"
echo "============================================="
echo ""
echo "📋 Variables de entorno a configurar en Render:"
echo ""
echo "MONGODB_URL="
echo "mongodb+srv://wiki:Ieu3REQOvv9frZK4@cluster0.3c9l9sw.mongodb.net/wikipedia_graph_explorer?retryWrites=true&w=majority&appName=Cluster0&tls=true&authSource=admin"
echo ""
echo "DATABASE_NAME="
echo "wikipedia_graph_explorer"
echo ""
echo "BACKEND_PORT="
echo "8000"
echo ""
echo "JWT_SECRET_KEY="
echo "your-super-secret-jwt-key-change-this-in-production-render"
echo ""
echo "LOG_LEVEL="
echo "INFO"
echo ""
echo "MAX_GRAPH_NODES="
echo "200"
echo ""
echo "MAX_GRAPH_DEPTH="
echo "3"
echo ""
echo "REQUEST_TIMEOUT="
echo "30"
echo ""
echo "WIKIPEDIA_USER_AGENT="
echo "Wikipedia-Graph-Explorer/1.0 (Educational Purpose)"
echo ""
echo "WIKIPEDIA_TIMEOUT="
echo "30"
echo ""
echo "📝 Instrucciones para Render:"
echo "=============================="
echo "1. Ve a tu servicio en Render Dashboard"
echo "2. Haz clic en 'Environment'"
echo "3. Agrega cada variable de entorno listada arriba"
echo "4. Guarda los cambios"
echo "5. Redeploy tu servicio"
echo ""
echo "🔧 Comandos de build para Render:"
echo "=================================="
echo "Build Command:"
echo "cd backend && pip install -r requirements.txt"
echo ""
echo "Start Command:"
echo "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
echo ""
echo "✅ ¡Configuración completa!"
